@MusicApp.API_HostAddress = http://localhost:5296

GET {{MusicApp.API_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{MusicApp.API_HostAddress}}/weatherforecast/
Accept: application/json

###
